# Generated by Django 5.2.6 on 2025-10-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('tipo', models.CharField(choices=[('JR', 'Jurídico'), ('CT', 'Contable')], max_length=2, verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Área de Servicio Principal',
                'verbose_name_plural': 'Áreas de Servicio Principales',
            },
        ),
        migrations.CreateModel(
            name='ServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='Nombre del Servicio Específico')),
                ('description', models.TextField(verbose_name='Descripcion Detallada del servicio')),
                ('priority', models.IntegerField(default=10, help_text='Menor número = mayor prioridad/orden.', verbose_name='Prioridad/Orden')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.areaservicio', verbose_name='Área de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle del Servicio',
                'verbose_name_plural': 'Detalles de Servicios',
                'ordering': ['priority'],
            },
        ),
    ]
