# Generated by Django 5.2.6 on 2025-10-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaservicio',
            options={'verbose_name': 'Área de Servicio Principal', 'verbose_name_plural': 'Áreas de Servicios Principales'},
        ),
        migrations.RenameField(
            model_name='areaservicio',
            old_name='tipo',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='serviciodetalle',
            name='description',
            field=models.TextField(verbose_name='Descripción Detallada del servicio'),
        ),
    ]
