# Generated by Django 5.2.6 on 2025-10-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_areaservicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaservicio',
            name='description',
            field=models.TextField(default='Descripción pendiente', verbose_name='Descripción del Área de Servicio'),
        ),
    ]
