# Generated by Django 5.2.6 on 2025-10-10 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_areaservicio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciodetalle',
            old_name='service_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='serviciodetalle',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='serviciodetalle',
            name='priority',
            field=models.PositiveSmallIntegerField(default=10, help_text='Menor número = mayor prioridad/orden.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridad/Orden'),
        ),
    ]
