# Generated by Django 5.2.6 on 2025-10-14 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('description', models.TextField(default='Descripción pendiente', verbose_name='Descripción del Área de Servicio')),
                ('type', models.CharField(choices=[('JR', 'Jurídico'), ('CT', 'Contable')], max_length=2, verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Área de Servicio Principal',
                'verbose_name_plural': 'Áreas de Servicios Principales',
            },
        ),
        migrations.CreateModel(
            name='ServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Servicio Específico')),
                ('description', models.TextField(verbose_name='Descripción Detallada del servicio')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Menor número = mayor prioridad/orden.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridad/Orden')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.areaservicio', verbose_name='Área de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle del Servicio',
                'verbose_name_plural': 'Detalles de Servicios',
                'ordering': ['priority'],
            },
        ),
    ]
