# Generated by Django 5.2.6 on 2025-10-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaservicio',
            options={'verbose_name': 'Área de Servicio', 'verbose_name_plural': 'Áreas de Servicio'},
        ),
        migrations.RenameField(
            model_name='areaservicio',
            old_name='type',
            new_name='area_type',
        ),
    ]
