# Generated by Django 5.2.6 on 2025-10-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Especialista', 'verbose_name_plural': 'Especialistas'},
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='type',
            new_name='area_type',
        ),
    ]
