# Generated by Django 5.2.6 on 2025-10-27 10:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MX', verbose_name='Número de Teléfono')),
                ('state', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Contactado'), ('CER', 'Cerrado')], default='PEN', max_length=3, verbose_name='Estado de la Consulta')),
                ('description', models.TextField(blank=True, verbose_name='Motivo de la Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviciodetalle', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-created_at'],
            },
        ),
    ]
